version: '3.7'

services:
# nginx-proxy #####################
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/ssl/certs:/etc/nginx/certs:ro
      - ./nginx/ssl/vhostd:/etc/nginx/vhost.d
      - ./nginx/ssl/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - app-network

# #letsencript
  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   environment:
  #     - NGINX_PROXY_CONTAINER=nginx-proxy
  #   volumes:
  #     - ./nginx/ssl/certs:/etc/nginx/certs:rw
  #     - ./snginx/sl/vhostd:/etc/nginx/vhost.d
  #     - ./nginx/ssl/html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - app-network


############## Proyecto AdmiApp ################
#Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80"
      - "443"
    volumes:
      - ./nginx/sites/:/etc/nginx/conf.d/
      - ./nginx/ssl/certs/:/etc/nginx/ssl/
      - ./alegra-proyect/:/var/www
    environment:
      - VIRTUAL_HOST=admiapp.co,www.admiapp.co
      - LETSENCRYPT_HOST=admiapp.co,www.admiapp.co
      - LETSENCRYPT_EMAIL=cesarago852@gmail.com
    networks:
      - app-network

#PHP Service
  app:
    build:
      context: ./alegra-proyect
      dockerfile: Dockerfile
    image: admiapp
    container_name: app
    restart: unless-stopped
    tty: true
    # environment:
    #   VIRTUAL_HOST: admiapp.com
    working_dir: /var/www
    volumes:
      - ./alegra-proyect:/var/www
    networks:
      - app-network

############## End Proyecto AdmiApp ################

############## proyect b ######################
# nginx server www #
############# End proyect b ######################
#Volumes
volumes:
  webserver:
    driver: local
  app:
    driver: local
  nginx_proxy:
    driver: local
  letsencript:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge
